//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT6_EnityFramework.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV1
    {
        public string MSSV { get; set; }
        public string NAMESV { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public Nullable<System.DateTime> NGAYSINH { get; set; }
        public Nullable<double> DTB { get; set; }
        public Nullable<int> ID_LOP { get; set; }
    
        public virtual LSH LSH { get; set; }
    }
}
